FinalEMR/Areas/Admin/Controllers/AllergyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using FinalEMR.DataAccess.Repository.IRepository;
using FinalEMR.Models;
using FinalEMR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;

namespace FinalEMR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Doctor + "," + SD.Role_Privi_Nurse + "," + SD.Role_Nurse)]
    public class AllergyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AllergyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Doctor + "," + SD.Role_Privi_Nurse)]
        public IActionResult Upsert(int? id)
        {
            Allergy allergy = new Allergy();
            if (id == null)
            {
                //this is for create
                return View(allergy);
            }
            //this is for edit
            var parameter = new DynamicParameters();
            parameter.Add(@"Id", id);
            allergy = _unitOfWork.SP_Call.OneRecord<Allergy>(SD.Proc_Allergy_Get, parameter);
            if (allergy == null)
            {
                return NotFound();
            }

            return View(allergy);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Allergy allergy)
        {
            if (ModelState.IsValid)
            {
                var parameter = new DynamicParameters();
                parameter.Add(@"Name", allergy.Name);

                if (allergy.Id == 0)
                {
                    //Adds new prescription
                    _unitOfWork.SP_Call.Execute(SD.Proc_Allergy_Create, parameter);
                }
                else
                {
                    parameter.Add(@"Id", allergy.Id);
                    _unitOfWork.SP_Call.Execute(SD.Proc_Allergy_Update, parameter);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(allergy);
        }

        #region API CAllS
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.SP_Call.List<Allergy>(SD.Proc_Allergy_GetAll, null);
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var parameter = new DynamicParameters();
            parameter.Add("@Id", id);
            var objFromDb = _unitOfWork.SP_Call.OneRecord<Allergy>(SD.Proc_Allergy_Get, parameter);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.SP_Call.Execute(SD.Proc_Allergy_Delete, parameter);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }
}

FinalEMR/Areas/Admin/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalEMR.DataAccess.Repository.IRepository;
using FinalEMR.Models;
using FinalEMR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;

namespace FinalEMR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Doctor + "," + SD.Role_Privi_Nurse)]
    public class DoctorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DoctorController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Upsert(int? id)
        {
            Doctor doctor = new Doctor();
            if (id == null)
            {
                //this is for create
                return View(doctor);
            }
            //this is for edit
            doctor = _unitOfWork.Doctor.Get(id.GetValueOrDefault());
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                if (doctor.Id == 0)
                {
                    //Adds new doctor
                    _unitOfWork.Doctor.Add(doctor);
                }
                else
                {
                    _unitOfWork.Doctor.Update(doctor);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        #region API CAllS
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Doctor.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Doctor.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Doctor.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }
}

FinalEMR/Areas/Admin/Controllers/NurseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalEMR.DataAccess.Repository.IRepository;
using FinalEMR.Models;
using FinalEMR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;

namespace FinalEMR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Doctor + "," + SD.Role_Privi_Nurse + "," + SD.Role_Nurse)]
    public class NurseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public NurseController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Doctor +  "," + SD.Role_Privi_Nurse)]
        public IActionResult Upsert(int? id)
        {
            Nurse nurse = new Nurse();
            if (id == null)
            {
                //this is for create
                return View(nurse);
            }
            //this is for edit
            nurse = _unitOfWork.Nurse.Get(id.GetValueOrDefault());
            if (nurse == null)
            {
                return NotFound();
            }

            return View(nurse);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Nurse nurse)
        {
            if (ModelState.IsValid)
            {
                if (nurse.Id == 0)
                {
                    //Adds new nurse
                    _unitOfWork.Nurse.Add(nurse);
                }
                else
                {
                    _unitOfWork.Nurse.Update(nurse);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(nurse);
        }

        #region API CAllS
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Nurse.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Nurse.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Nurse.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }
}

FinalEMR/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalEMR.DataAccess.Data;
using FinalEMR.DataAccess.Repository.IRepository;
using FinalEMR.Models;
using FinalEMR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.EntityFrameworkCore;

namespace FinalEMR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        //directrly Using Application Db Context vs. Repository Pattern
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }


        #region API CAllS
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.Include(u => u.Doctor).Include(m => m.Nurse).ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if (user.Doctor == null)
                {
                    //So Doctor Value doesn't throw error when creating user as admin
                    user.Doctor = new Doctor()
                    {
                        Name = ""
                    };
                }
                if (user.Nurse == null)
                {
                    //So Nurse Value doesn't throw error when creating user as admin
                    user.Nurse = new Nurse()
                    {
                        Name = ""
                    };
                }

            }
            return Json(new { data = userList, });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }
            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is curretly lockedout, we will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Operation Successful" });
        }
        #endregion
    }
}

FinalEMR/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FinalEMR/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FinalEMR/Views/Shared/_Layout.cshtml
@using FinalEMR.Utility 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMR</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin) || (User.IsInRole(SD.Role_Doctor)))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Prescription" asp-action="Index">Prescription</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Allergy" asp-action="Index">Allergy</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Patient" asp-action="Index">Patient</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Privi_Nurse) || User.IsInRole(SD.Role_Nurse))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Prescription" asp-action="Index">Prescription</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Allergy" asp-action="Index">Allergy</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Patient" asp-action="Index">Patient</a>
                                </div>
                            </li>
                        } 
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User / Doctor
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Doctor" asp-action="Index">Doctor</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Nurse" asp-action="Index">Nurse</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Doctor) || User.IsInRole(SD.Role_Privi_Nurse))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User / Doctor
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Doctor" asp-action="Index">Doctor</a>
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Nurse" asp-action="Index">Nurse</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Nurse))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User / Doctor
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-black-50" asp-area="Admin" asp-controller="Nurse" asp-action="Index">Nurse</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2020 - EMR
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>